### PR TITLE
Customize Bootstrap

### PR DESCRIPTION
**Pull request by scottmacphersonmusic**
Include only the bootstrap features that are actually getting used.

### CODE REVIEW

**Comment by scottmacphersonmusic** [comment]
@bion does this satisfy the issue you brought up or should I be cutting out some of the unused CSS files as well?

**Comment by bion** [comment]
You should be able to do this without checking everything in like that. Did you look at the README link I provided?

**Comment by scottmacphersonmusic** [comment]
I did read that README but didn't entirely understand at the time, and so went down a several-hours-long yak shaving mission leading to a better understanding of the asset pipeline, manifest files/directives, and the bootstrap source.  

Looking at the README again I think I get it now - I'm now pulling specific modules out of the gem with `@import` statements in `_bootstrap-custom.sass`.  So far I don't think I'm using any of the JS modules, and so haven't included them.

My main concern now is trying to figure out which of the `.scss` modules I'm dependent on.  I've been scouring the bootstrap component documentation, but the most effective method still seems to be guess-and-check, i.e. comment out a line and then look around the site to see if anything changed.  Do you have any recommendations on that front?

**Comment by bion** [comment]
I don't know of a better way of doing it off the top of my head. The Bootstrap docs should tell you which modules provide what. You may also see if someone has made any gems to help with the process.

Looks like you're almost done though!

**Comment by scottmacphersonmusic** [comment]
As far as I can tell (once I turn off the Evernote and Vimium extensions) all of the requests are necessary/intentional.  `favicon.ico` was initially a mystery but I have since learned that all browsers include it and all I can do is replace it with my own image at some point down the road.  

I'm gonna merge it!

**Comment by bion** [comment]
:+1:

**Pull request merged**
